export const LEGAL_PRIVACY_EN = {
  title: "AGROBRIDGE PRIVACY POLICY",
  version: "1.0",
  effectiveDate: "20 September 2026",
  ready: true,
  paragraphs: [
    "**Version:** 1.0",
    "**Effective date:** 20 September 2026",
    "## 1. Who We Are",
    "This Privacy Policy explains how AgroBridge processes personal data when you use the AgroBridge website, marketplace, account features, communication tools and related services.",
    "AgroBridge is operated by:",
    "**P/E VANO MEGVINETUKHUTSESI**",
    "Legal form: Individual Entrepreneur",
    "Registered address: 29/5 Adam Mitskevichi Street, Tbilisi, Georgia",
    "Identification number: 01501157152",
    "Email: [support@agrobridge.ge](mailto:support@agrobridge.ge)",
    "Website: [https://agrobridge.ge](https://agrobridge.ge/)",
    "For the purposes of applicable Georgian personal data protection law, the operator determines the purposes and means of processing personal data performed through AgroBridge and acts as the relevant controller where applicable.",
    "This Privacy Policy applies to personal data processed through AgroBridge. It does not govern the independent processing of personal data by other users, buyers, sellers or third-party websites or services.",
    "## 2. What Personal Data We Process",
    "Depending on how you use AgroBridge, we may process the following categories of personal data.",
    "## 2.1 Account and profile data",
    "This may include:",
    "- email address;",
    "- display name;",
    "- profile photograph or avatar, if provided;",
    "- preferred interface language;",
    "- account role and buyer/seller type;",
    "- account-related identifiers;",
    "- information you provide in your profile or farm profile.",
    "Your email address is used for authentication and communication. It is not included in the standard public profile responses.",
    "## 2.2 Contact and verification data",
    "Where you voluntarily use manufacturer or farm verification features, we may process:",
    "- telephone number;",
    "- information confirming email or telephone verification;",
    "- company registration number;",
    "- uploaded identity documents;",
    "- uploaded business registration documents;",
    "- other documents you choose to submit for verification;",
    "- information and notes generated during the verification process.",
    "Verification documents are not part of the public farm profile and are restricted to authorised access, including the relevant farm owner and authorised administrators.",
    "AgroBridge does not use biometric identification or facial-recognition systems as part of the current verification process.",
    "## 2.3 Farm and business information",
    "Depending on the information you provide, this may include:",
    "- farm name;",
    "- region and locality;",
    "- description and history;",
    "- farm size;",
    "- ownership type;",
    "- year established;",
    "- export markets;",
    "- business or company information;",
    "- verification status.",
    "Some farm and business information may be publicly displayed as part of the marketplace.",
    "## 2.4 Marketplace information",
    "When you publish or respond to marketplace activity, we may process:",
    "- Purchase Request information;",
    "- product information;",
    "- quantities;",
    "- destinations;",
    "- prices;",
    "- messages and descriptions;",
    "- Offers and RFQ information;",
    "- transaction-related marketplace information;",
    "- information identifying the relevant buyer or seller.",
    "Some Purchase Request and marketplace information is intentionally public. In particular, an open Purchase Request may include the author's display name and free-text message.",
    "Users should therefore avoid placing unnecessary personal or confidential information in publicly visible marketplace fields.",
    "## 2.5 Communications",
    "If you use AgroBridge communication features, we may process:",
    "- message text;",
    "- sender and recipient identifiers;",
    "- language information;",
    "- limited message previews used for notifications;",
    "- related timestamps and technical metadata.",
    "Messages are available to the relevant participants. Authorised administrators may have access to conversations where necessary for platform administration, moderation or support.",
    "## 2.6 Ratings and reviews",
    "If the relevant functionality is used, we may process:",
    "- rating scores;",
    "- review comments;",
    "- the display name and identifier of the person submitting the rating;",
    "- related marketplace information.",
    "Ratings and review comments may be publicly visible.",
    "## 2.7 Notifications and subscriptions",
    "We may process information required to provide:",
    "- in-app notifications;",
    "- marketplace notifications;",
    "- email alerts;",
    "- product or harvest-related alerts where you have enabled them;",
    "- notification read/unread status;",
    "- subscription preferences.",
    "## 2.8 Support requests",
    "If you contact AgroBridge through a support form, we may receive:",
    "- your name;",
    "- email address;",
    "- subject;",
    "- message content.",
    "Support requests are sent to the configured support mailbox and are not currently stored as a separate record in the AgroBridge application database.",
    "## 3. Authentication and Security Information",
    "To operate accounts securely, AgroBridge processes certain authentication and security information.",
    "This may include:",
    "- password hashes;",
    "- authentication tokens;",
    "- account security version information;",
    "- password-reset token hashes;",
    "- one-time verification code hashes;",
    "- email or telephone destinations used for verification;",
    "- anti-abuse and rate-limiting information.",
    "Passwords are not stored in plain text.",
    "AgroBridge uses an authentication cookie named agrobridge_token. The cookie contains an authentication token whose current payload includes information such as the account identifier, email address, role, language and authentication version.",
    "The authentication cookie is intended to be necessary for account functionality. It is not used for advertising or behavioural tracking.",
    "## 4. IP Addresses and Technical Information",
    "AgroBridge may process IP address information for security, abuse prevention and rate limiting.",
    "The application does not store a plain-text IP address as a normal user-profile field. Rate-limiting information uses a derived representation rather than storing the plain-text IP address in the relevant database record.",
    "Network traffic to AgroBridge may also pass through infrastructure providers such as Cloudflare and hosting infrastructure. These providers may receive network and technical information, including IP addresses, as part of delivering and securing the service.",
    "AgroBridge does not currently use the User-Agent as a user-profile field or as a separate application data record.",
    "## 5. Cookies and Similar Technologies",
    "AgroBridge currently uses necessary first-party cookies for core functionality.",
    "## Authentication cookie",
    "agrobridge_token is used to maintain an authenticated session.",
    "## Language cookie",
    "AgroBridge currently uses the NEXT_LOCALE cookie to remember the selected interface language.",
    "This cookie contains a language code such as en, ka, ru or another supported locale. It does not contain your name, email address or account identifier.",
    "AgroBridge does not currently use Google Analytics, Meta Pixel, Hotjar, Sentry, PostHog or similar advertising/analytics tracking pixels in the web application.",
    "## 6. Files, Images and Documents",
    "AgroBridge may process files that you upload, including:",
    "- farm photographs;",
    "- profile photographs;",
    "- product photographs;",
    "- product videos;",
    "- verification documents;",
    "- business registration documents;",
    "- product certificates.",
    "Public marketplace media may be accessible without authentication.",
    "Verification documents are stored separately from public farm information and are subject to access controls.",
    "Uploaded files may contain metadata embedded in the file itself. AgroBridge's current upload flow does not remove EXIF metadata from images.",
    "AgroBridge does not currently perform automated malware scanning of uploaded files.",
    "## 7. How We Use Personal Data",
    "We process personal data for purposes including:",
    "1. creating and maintaining user accounts;",
    "2. authenticating users;",
    "3. providing marketplace functionality;",
    "4. publishing and displaying marketplace information;",
    "5. enabling communication between users;",
    "6. providing notifications and alerts;",
    "7. verifying users or farms where voluntary verification is requested;",
    "8. administering and moderating the platform;",
    "9. preventing abuse and protecting platform security;",
    "10. responding to support requests;",
    "11. recording acceptance of the Terms of Use;",
    "12. maintaining, securing and operating AgroBridge;",
    "13. complying with applicable legal obligations where required.",
    "We do not use personal data for purposes incompatible with the purposes described in this Policy unless permitted or required by applicable law and appropriately communicated.",
    "## 8. Legal Grounds for Processing",
    "The legal ground for processing depends on the particular processing activity.",
    "Where applicable, processing may be based on:",
    "- the performance of a contract or taking steps at your request before entering into a contract;",
    "- your consent, where consent is required;",
    "- compliance with a legal obligation;",
    "- another legal ground permitted by applicable Georgian law, where applicable.",
    "AgroBridge determines and applies the appropriate legal ground to the relevant processing activity.",
    "Providing certain data may be necessary to create an account, provide a requested service, complete verification or perform a requested action. If required information is not provided, the relevant feature or service may not be available.",
    "Where processing is based on consent, you may withdraw that consent subject to applicable law. Withdrawal does not affect processing that has another valid legal ground.",
    "## 9. Public Information",
    "AgroBridge is a marketplace and therefore some information is intentionally made available to other users or the public.",
    "Depending on the feature, publicly accessible information may include:",
    "- display name;",
    "- profile and farm information;",
    "- farm photographs;",
    "- product information;",
    "- Purchase Requests;",
    "- marketplace messages entered into public fields;",
    "- ratings and review comments;",
    "- verification status;",
    "- certain product certificates where the relevant product is approved and published.",
    "Email addresses, telephone numbers and verification documents are not included in the normal public farm or user profile responses.",
    "You should not publish personal, confidential or sensitive information in fields intended to be publicly visible.",
    "## 10. Sharing and Disclosure of Personal Data",
    "We may disclose or make personal data available to the following categories of recipients where necessary for the purposes described in this Policy:",
    "## Other AgroBridge users",
    "Information intentionally published through marketplace profiles, Purchase Requests, products, ratings or other public features may be visible to other users or visitors.",
    "Information required to conduct marketplace communications may be shared with the relevant participants.",
    "## Administrators and authorised personnel",
    "Authorised AgroBridge administrators may access information necessary for moderation, verification, security, support and platform administration.",
    "This may include verification documents and user communications where access is authorised.",
    "## Infrastructure and service providers",
    "AgroBridge uses third-party infrastructure and service providers where necessary to operate the platform. Depending on the active production configuration, these may include providers for:",
    "- hosting and application infrastructure;",
    "- database services;",
    "- network security, CDN and traffic protection;",
    "- object storage;",
    "- email delivery;",
    "- SMS delivery;",
    "- location/place search services.",
    "The exact providers and configurations may change as the platform develops.",
    "Where a third party processes personal data on behalf of AgroBridge, AgroBridge seeks to use appropriate contractual, organisational and technical arrangements required by applicable law.",
    "## 11. Email and SMS Services",
    "AgroBridge may use external email and SMS services to deliver:",
    "- account and verification messages;",
    "- password-reset messages;",
    "- marketplace notifications;",
    "- offer and Purchase Request notifications;",
    "- support communications;",
    "- other service-related communications.",
    "Email messages may contain information necessary to provide the relevant service, such as your display name or email address, marketplace information, prices, or limited message previews.",
    "SMS verification, where enabled, may involve sending your telephone number and a one-time verification code to the relevant SMS service provider.",
    "The specific provider used for a particular service may depend on the current production configuration.",
    "## 12. External APIs and Services",
    "Certain AgroBridge features may use external APIs.",
    "For example, where place-search functionality is enabled, a search query entered by the user may be sent from the AgroBridge server to a place-search provider to return locality suggestions.",
    "The current chat message flow does not send user messages to OpenAI for translation.",
    "AgroBridge does not currently use payment processors, payment cards or bank-account processing for marketplace transactions.",
    "## 13. International Data Transfers",
    "Because AgroBridge uses cloud, hosting, network, communication and other technology providers, personal data may potentially be processed outside Georgia depending on the provider and production configuration.",
    "The geographic location of all production processing and storage cannot always be determined solely from the AgroBridge application.",
    "Where personal data is transferred to another country or international organisation, AgroBridge will apply the requirements and safeguards required by applicable Georgian law.",
    "## 14. Data Retention",
    "AgroBridge does not currently apply one universal retention period to all categories of personal data.",
    "Retention depends on the type of information and the purpose for which it is processed.",
    "Examples include:",
    "- authentication and verification tokens are subject to technical expiration periods;",
    "- rate-limiting records may remain until their technical expiration;",
    "- account information is generally retained while the account exists;",
    "- marketplace and communication records may be deleted when an account is deleted where the application is designed to cascade-delete them;",
    "- uploaded files are subject to deletion processes associated with account deletion, but deletion of an external storage object is currently performed on a best-effort basis;",
    "- third-party service providers may retain information in accordance with their own applicable policies and contractual arrangements.",
    "Where a specific retention period cannot reasonably be established in advance, retention criteria include the purpose of processing, the continued need for the information, legal obligations, dispute resolution and security requirements.",
    "## 15. Account Deletion",
    "You may request deletion of your AgroBridge account through the account functionality provided by AgroBridge.",
    "Account deletion currently results in deletion of the user record and associated application records according to the database relationships and deletion process used by AgroBridge.",
    "This may include farm information, marketplace records, messages, ratings, notifications and Terms acceptance records associated with the account.",
    "Uploaded files are subject to a separate best-effort storage deletion process. AgroBridge therefore does not represent that every copy of every externally stored file will always be physically removed immediately.",
    "Technical rate-limiting records and information already delivered to other parties or retained by external service providers may remain for their applicable technical or legal periods.",
    "Deleting an account may also remove conversations for the other participant where the conversation is linked to the deleted account.",
    "## 16. Data Security",
    "AgroBridge uses technical and organisational measures appropriate to the nature and risks of the processing.",
    "Current measures include, among others:",
    "- password hashing;",
    "- authenticated access controls;",
    "- access restrictions for verification documents;",
    "- hashed password-reset and verification tokens;",
    "- authentication-token invalidation mechanisms;",
    "- rate limiting and abuse prevention;",
    "- HTTPS for production web and API traffic;",
    "- separation of public and private file storage/access paths.",
    "No online service can guarantee absolute security. Users should also protect their account credentials and avoid submitting unnecessary confidential information through publicly visible marketplace fields.",
    "## 17. Automated Decision-Making",
    "AgroBridge does not currently use solely automated decision-making that produces legal or similarly significant effects on users.",
    "Human administrators may participate in verification, moderation and other platform decisions.",
    "## 18. Your Rights",
    "Subject to the conditions and limitations established by applicable Georgian law, you may have rights including:",
    "- to obtain information about the processing of your personal data;",
    "- to access your personal data and obtain copies;",
    "- to request correction or updating of inaccurate data;",
    "- to request deletion where legally applicable;",
    "- to request restriction or blocking of processing where legally applicable;",
    "- to withdraw consent where processing is based on consent;",
    "- to receive or request transmission of certain data in a structured, commonly used and machine-readable format where the legal requirements are met and technically feasible;",
    "- to object to or otherwise exercise rights concerning certain processing activities where provided by law;",
    "- to exercise rights concerning solely automated decision-making where applicable;",
    "- to lodge a complaint with the competent Georgian data protection authority or seek judicial protection where provided by law.",
    "Some rights may be subject to legal limitations or may not apply to every processing activity.",
    "## 19. How to Exercise Your Rights",
    "For privacy-related requests, contact:",
    "[**support@agrobridge.ge**](mailto:support@agrobridge.ge)",
    "Please describe your request sufficiently for AgroBridge to identify the relevant account or information.",
    "AgroBridge may take reasonable steps to verify the identity of the person making a request before disclosing or changing personal data.",
    "Requests will be handled within the time limits and according to the procedures established by applicable law.",
    "## 20. Children",
    "AgroBridge is intended for users who are legally capable of entering into the relevant agreements and using the service under applicable law.",
    "AgroBridge does not intentionally request a date of birth or maintain a dedicated age-verification system.",
    "If you believe that personal data of a child has been provided to AgroBridge unlawfully, please contact us at [support@agrobridge.ge](mailto:support@agrobridge.ge).",
    "## 21. Third-Party Websites and Services",
    "AgroBridge may contain links or integrations involving third-party websites or services.",
    "Their privacy practices are governed by their own policies.",
    "AgroBridge is not responsible for the privacy practices of independent third parties or for personal data that users provide directly to them.",
    "## 22. Changes to This Privacy Policy",
    "We may update this Privacy Policy when AgroBridge changes its services, processing activities, infrastructure or legal requirements.",
    "The current version and effective date will be displayed on the AgroBridge website.",
    "Where a material change requires additional action or notification under applicable law, AgroBridge will take the measures required by law.",
    "## 23. Contact",
    "For questions, requests or concerns regarding personal data:",
    "**P/E VANO MEGVINETUKHUTSESI**",
    "29/5 Adam Mitskevichi Street",
    "Tbilisi, Georgia",
    "Identification number: 01501157152",
    "Email: [support@agrobridge.ge](mailto:support@agrobridge.ge)",
    "Website: [https://agrobridge.ge](https://agrobridge.ge/)",
    "**Version:** 1.0",
    "**Effective date:** 20 September 2026",
  ],
};
