export const LEGAL_TERMS_EN = {
  title: "AGROBRIDGE TERMS OF USE",
  version: '1.0',
  effectiveDate: "20 September 2026",
  ready: true,
  paragraphs: [
    "**Version:** 1.0",
    "**Effective date:** 20 September 2026",
    "## 1. Operator and Contact Information",
    "These Terms of Use (\"Terms\") govern your access to and use of the AgroBridge platform and services available at [**https://agrobridge.ge**](https://agrobridge.ge/) (\"AgroBridge\", \"Platform\", \"we\", \"us\" or \"our\").",
    "The Platform is operated by:",
    "**P/E VANO MEGVINETUKHUTSESI**",
    "**Legal form:** Individual Entrepreneur",
    "**Registered address:** 29/5 Adam Mitskevichi Street, Tbilisi, Georgia",
    "**Identification number:** 01501157152",
    "**Email:** [support@agrobridge.ge](mailto:support@agrobridge.ge)",
    "**Website:** [https://agrobridge.ge](https://agrobridge.ge/)",
    "AgroBridge is an online agricultural marketplace and intermediary platform intended to facilitate connections between agricultural producers, suppliers, buyers and other participants in agricultural trade.",
    "## 2. About AgroBridge",
    "AgroBridge provides digital marketplace and intermediary services that allow users to discover agricultural products and suppliers, publish purchase requests, submit offers, communicate with other users and use other features made available through the Platform.",
    "AgroBridge operates as a technology platform and intermediary service.",
    "Unless expressly stated otherwise, AgroBridge does not itself sell, purchase, manufacture, own, store, transport or deliver the agricultural products listed or discussed by users.",
    "These Terms govern your relationship with AgroBridge and your use of the Platform. They do not constitute the terms of sale or supply between a buyer and a seller.",
    "## 3. AgroBridge Is Not a Party to User Transactions",
    "Transactions between buyers and sellers are made directly between the relevant users.",
    "AgroBridge is not a seller, buyer, agent, broker acting on behalf of either party, payment recipient, escrow provider or party to a contract for the sale or supply of products between users, unless AgroBridge expressly agrees otherwise in a separate written agreement.",
    "AgroBridge does not guarantee that:",
    "- a Purchase Request will receive an offer;",
    "- an offer will be accepted;",
    "- a user will complete a transaction;",
    "- a product will be available;",
    "- a product will meet a particular quality, quantity or specification;",
    "- payment will be made;",
    "- delivery will take place; or",
    "- a transaction between users will be completed successfully.",
    "Users are responsible for evaluating the other party and agreeing on the terms of their transaction.",
    "## 4. Eligibility and User Accounts",
    "You may use AgroBridge only if you are legally capable of entering into the applicable agreements under the laws applicable to you.",
    "When creating an account, you must provide information that is accurate and not misleading.",
    "You are responsible for:",
    "- maintaining the confidentiality of your login credentials;",
    "- keeping your account information reasonably accurate and up to date;",
    "- activities carried out through your account; and",
    "- promptly informing AgroBridge if you believe that your account has been accessed without authorization.",
    "An AgroBridge account may be used for both purchasing and selling activities. Any role or preference selected during registration does not prevent the user from using other permitted Platform functions.",
    "## 5. Platform Services",
    "Depending on the features available to you, AgroBridge may allow you to:",
    "- create and manage a user profile;",
    "- create and publish Purchase Requests;",
    "- browse Purchase Requests;",
    "- submit offers in response to Purchase Requests;",
    "- manage submitted offers;",
    "- communicate with other users;",
    "- publish information about agricultural products or production activities; and",
    "- use other marketplace and communication features introduced by AgroBridge.",
    "AgroBridge may add, modify or discontinue particular Platform features as the service develops.",
    "## 6. Purchase Requests",
    "A Purchase Request is a request published by a user seeking a product or supply opportunity.",
    "A Purchase Request may include information such as:",
    "- product;",
    "- quantity;",
    "- specifications;",
    "- location;",
    "- expected timing;",
    "- requirements; and",
    "- other information provided by the requesting user.",
    "Publication of a Purchase Request does not itself create a purchase contract.",
    "Users are responsible for ensuring that information contained in their Purchase Requests is accurate and lawful.",
    "## 7. Offers",
    "A seller or other eligible user may submit an offer in response to a Purchase Request.",
    "An offer may include information such as:",
    "- offered product;",
    "- quantity;",
    "- price;",
    "- delivery or collection information;",
    "- timing;",
    "- product specifications; and",
    "- other proposed conditions.",
    "Submitting an offer does not guarantee that the buyer will accept it.",
    "## 8. Acceptance of an Offer",
    "Where AgroBridge provides a function allowing a buyer to accept an offer, the buyer may use that function to record their acceptance of the offer through the Platform.",
    "Acceptance of an offer through AgroBridge does not by itself confirm:",
    "- payment;",
    "- delivery or collection;",
    "- transfer of ownership;",
    "- completion of the transaction; or",
    "- fulfilment of the parties' obligations.",
    "Whether an accepted offer constitutes a binding contract between the buyer and seller depends on the circumstances of their transaction and applicable law.",
    "AgroBridge is not a party to any contract between a buyer and seller.",
    "Unless the parties expressly agree otherwise, the buyer and seller remain responsible for establishing and fulfilling the terms governing their transaction, including applicable terms concerning:",
    "- product;",
    "- quantity;",
    "- price;",
    "- quality and specifications;",
    "- payment;",
    "- delivery or collection;",
    "- timing;",
    "- documentation; and",
    "- other relevant conditions.",
    "## 9. Agreements Between Users",
    "Users are responsible for deciding whether to enter into a transaction with another user.",
    "Where a buyer and seller enter into a separate agreement, that agreement is between those parties.",
    "Users should independently assess the identity, authority, reliability, products, documents and other relevant information of the other party before entering into a transaction.",
    "AgroBridge may provide tools that facilitate communication or exchange of information, but these tools do not replace the parties' responsibility to conduct their own due diligence.",
    "## 10. User Content and Information",
    "Users may submit, upload or publish information through AgroBridge, including descriptions, photographs, product information, business information, documents and other materials (\"User Content\").",
    "You are responsible for the User Content that you submit or publish.",
    "You must not knowingly provide information that is materially false, misleading or unlawful.",
    "You must have the necessary rights and permissions to submit User Content to AgroBridge and to permit AgroBridge to use that content for the operation and provision of the Platform.",
    "By submitting User Content, you grant AgroBridge a non-exclusive permission to host, store, reproduce, display, process and otherwise use that content solely to the extent reasonably necessary to provide, operate, maintain, secure and improve the Platform and its features.",
    "This permission does not transfer ownership of your User Content to AgroBridge.",
    "AgroBridge may take appropriate action regarding User Content where required by applicable law or where reasonably necessary to operate or protect the Platform.",
    "## 11. Prohibited Use",
    "You must not use AgroBridge to:",
    "- engage in unlawful activities;",
    "- commit or facilitate fraud;",
    "- impersonate another person or entity;",
    "- knowingly provide materially false or misleading information;",
    "- infringe intellectual property, privacy or other rights of another person;",
    "- distribute malware or other malicious software;",
    "- interfere with the security or operation of the Platform;",
    "- attempt to gain unauthorized access to accounts, systems or data;",
    "- use the Platform for spam or abusive communications;",
    "- circumvent technical or access restrictions;",
    "- collect or use other users' information unlawfully; or",
    "- otherwise misuse the Platform or use it in violation of applicable law.",
    "## 12. Communications Between Users",
    "AgroBridge may provide communication functionality that allows users to contact one another in connection with marketplace activities.",
    "Users are responsible for the content and legality of their communications.",
    "Users must not use AgroBridge communication tools for unlawful, fraudulent, abusive or misleading purposes.",
    "AgroBridge may take appropriate measures concerning communications where required by law or reasonably necessary to protect the Platform, its users or third parties.",
    "## 13. Platform Availability and Changes",
    "AgroBridge aims to keep the Platform available and functional but does not guarantee uninterrupted or error-free operation.",
    "The Platform may occasionally be unavailable because of maintenance, updates, technical issues, security measures, infrastructure failures or circumstances beyond AgroBridge's reasonable control.",
    "AgroBridge may modify, improve, suspend or discontinue particular Platform features as the service develops.",
    "Where a material change affects these Terms or the rights and obligations of users, AgroBridge will handle the change in accordance with applicable legal requirements and the Platform's legal-document versioning process.",
    "## 14. Intellectual Property",
    "The AgroBridge name, branding, logo, software, interface, design and other materials created or provided by AgroBridge are owned by or licensed to AgroBridge or their respective rights holders, unless otherwise stated.",
    "These materials may not be copied, modified, distributed, reproduced or commercially exploited without the necessary authorization, except where permitted by applicable law.",
    "Nothing in these Terms transfers ownership of AgroBridge intellectual property to a user.",
    "User Content remains subject to the rights of the respective user or other rights holder, subject to the permission granted to AgroBridge under these Terms.",
    "## 15. Account Suspension and Termination",
    "You may stop using AgroBridge at any time and may request closure of your account through the available account functionality or by contacting AgroBridge.",
    "AgroBridge may restrict, suspend or terminate access to an account where reasonably necessary, including where:",
    "- the user materially violates these Terms;",
    "- the user uses the Platform unlawfully;",
    "- the account presents a security risk;",
    "- the user's conduct materially threatens the Platform or other users; or",
    "- such action is required by applicable law.",
    "Where appropriate and legally permitted, AgroBridge may provide the user with an opportunity to address the relevant issue before access is restricted or terminated.",
    "Termination of an account does not automatically terminate obligations that by their nature should continue after termination.",
    "## 16. Electronic Communications and Contracts",
    "AgroBridge operates through electronic means.",
    "By using the Platform, you acknowledge that communications, notices and other information may be provided electronically through the Platform or by email where applicable.",
    "These Terms are made available electronically and may be accepted electronically through the Platform.",
    "Where AgroBridge provides functionality through which an electronic contract may be concluded with AgroBridge, the Platform will provide the information and technical means required by applicable law before that contract is concluded.",
    "This may include information concerning:",
    "- the technical steps required to conclude the contract;",
    "- the electronic storage and accessibility of the contract;",
    "- the languages available for concluding the contract; and",
    "- the technical means available to identify and correct errors before final submission.",
    "Where applicable, users will be provided with the ability to store or otherwise access information and contracts provided to them electronically.",
    "The conclusion of a contract between a buyer and seller through or in connection with the Platform is governed by the terms agreed between those parties and applicable law.",
    "## 17. Third-Party Services",
    "AgroBridge may rely on third-party service providers to support technical, hosting, communication, security, analytics or other functions necessary to operate the Platform.",
    "The processing of personal data in connection with such services is addressed in the AgroBridge Privacy Policy where applicable.",
    "AgroBridge does not become responsible for products or services independently provided by third parties merely because they are accessible through or connected to the Platform.",
    "## 18. Personal Data",
    "AgroBridge processes personal data in accordance with applicable data protection legislation and the AgroBridge Privacy Policy.",
    "The Privacy Policy explains the categories of personal data processed, the purposes and legal bases of processing, relevant user rights and other information required by applicable data protection law.",
    "The Privacy Policy is a separate legal document and is not replaced by these Terms.",
    "## 19. Compliance with Applicable Law",
    "Users must comply with the laws and regulations applicable to their use of AgroBridge and to any transaction they conduct through the Platform.",
    "Nothing in these Terms is intended to exclude or limit any rights or protections that cannot lawfully be excluded or limited under applicable law.",
    "## 20. Changes to These Terms",
    "AgroBridge may update these Terms when necessary, including when the Platform, its services or applicable legal requirements change.",
    "Each published version of the Terms will be identified by a version number and effective date.",
    "When a new version requires user acceptance under applicable law or AgroBridge's registration process, the Platform may require the user to review and accept the new version before continuing to use relevant services.",
    "Previous versions may be retained as part of AgroBridge's legal-document and acceptance records.",
    "## 21. Severability",
    "If any provision of these Terms is determined to be invalid or unenforceable under applicable law, the remaining provisions will remain in effect to the extent permitted by law.",
    "## 22. Contact",
    "For questions concerning these Terms or the AgroBridge Platform, please contact:",
    "**Email:** [support@agrobridge.ge](mailto:support@agrobridge.ge)",
    "**Website:** [https://agrobridge.ge](https://agrobridge.ge/)",
    "Additional operator information is provided on the AgroBridge website as required by applicable law.",
    "**Version:** 1.0",
    "**Effective date:** 20 September 2026",
  ],
};
