import { DEFAULT_LOCALE, isLocale, type Locale } from './locales';

/** Canonical English description → localized display text (en omitted; falls back to key). */
export const PRODUCT_DESCRIPTION_I18N: Record<
  string,
  Partial<Record<Locale, string>>
> = {
  'Seasonal freestone peaches, hand-picked for export.': {
    ka: 'სეზონური თავისუფალი ატამი, ხელით შერჩეული ექსპორტისთვის.',
    ru: 'Сезонные персики свободной косточки, собранные вручную на экспорт.',
    de: 'Saisonale Freistein-Pfirsiche, handverlesen für den Export.',
    fr: 'Pêches de saison à noyau libre, cueillies à la main pour l’export.',
    it: 'Pesche stagionali a nocciolo libero, raccolte a mano per l’export.',
    es: 'Melocotones de temporada de hueso libre, recolectados a mano para exportación.',
  },
  'Sweet seedless mandarins from Guria hillside groves.': {
    ka: 'ტკბილი უთესლო მანდარინი გურიის გორაკებიდან.',
    ru: 'Сладкие бессемянные мандарины с холмов Гурии.',
    de: 'Süße kernlose Mandarinen aus Guria-Hanglagen.',
    fr: 'Mandarines douces sans pépins des coteaux de Guria.',
    it: 'Mandarini dolci senza semi dai pendii di Guria.',
    es: 'Mandarinas dulces sin semillas de las laderas de Guria.',
  },
  'Crisp late-season apples, sorted for retail packing.': {
    ka: 'ხრაშუნა გვიანი სეზონის ვაშლი, დახარისხებული რითეილისთვის.',
    ru: 'Хрустящие поздние яблоки, отсортированные для розничной упаковки.',
    de: 'Knackige Spätsaison-Äpfel, sortiert für den Einzelhandel.',
    fr: 'Pommes croquantes de fin de saison, triées pour le retail.',
    it: 'Mele croccanti di fine stagione, selezionate per il retail.',
    es: 'Manzanas crujientes de final de temporada, clasificadas para retail.',
  },
  'Sweet persimmons, sorted for fresh packing and drying.': {
    ka: 'ტკბილი ხურმა, დახარისხებული ახალი შეფუთვისა და გამშრობისთვის.',
    ru: 'Сладкая хурма, отобранная для свежей упаковки и сушки.',
    de: 'Süße Kakis, sortiert für Frischpackung und Trocknung.',
    fr: 'Kakis sucrés, triés pour emballage frais et séchage.',
    it: 'Cachi dolci, selezionati per confezionamento fresco e essiccazione.',
    es: 'Caquis dulces, clasificados para envasado fresco y secado.',
  },
  'Cluster tomatoes with firm flesh for wholesale.': {
    ka: 'მტევნის პომიდორი მკვრივი რბილობით საბითუმო გაყიდვისთვის.',
    ru: 'Томаты кистью с плотной мякотью для опта.',
    de: 'Rispen-Tomaten mit festem Fruchtfleisch für den Großhandel.',
    fr: 'Tomates en grappe à chair ferme pour le gros.',
    it: 'Pomodori a grappolo con polpa soda per il wholesale.',
    es: 'Tomates en racimo de carne firme para mayoristas.',
  },
  'Washed table potatoes, graded by size.': {
    ka: 'გამორეცხილი სასუფრე კარტოფილი, დახარისხებული ზომით.',
    ru: 'Мытый столовый картофель, калиброванный по размеру.',
    de: 'Gewaschene Speisekartoffeln, nach Größe sortiert.',
    fr: 'Pommes de terre de table lavées, calibrées par taille.',
    it: 'Patate da tavola lavate, calibrate per dimensione.',
    es: 'Patatas de mesa lavadas, calibradas por tamaño.',
  },
  'Color mix of sweet peppers, harvest-to-order packing.': {
    ka: 'ტკბილი წიწაკის ფერადი ნაზავი, შეფუთვა შეკვეთის მიხედვით.',
    ru: 'Цветной микс сладкого перца, упаковка под заказ.',
    de: 'Bunter Süßpaprika-Mix, Verpackung auf Bestellung.',
    fr: 'Mélange coloré de poivrons doux, emballage sur commande.',
    it: 'Mix colorato di peperoni dolci, confezionamento su ordine.',
    es: 'Mezcla de colores de pimientos dulces, embalaje bajo pedido.',
  },
  'Crisp field cucumbers for HORECA and retail.': {
    ka: 'ხრაშუნა მინდვრის კიტრი HORECA-სა და რითეილისთვის.',
    ru: 'Хрустящие полевые огурцы для HORECA и ритейла.',
    de: 'Knackige Freilandgurken für HORECA und Einzelhandel.',
    fr: 'Concombres croquants de plein champ pour HORECA et retail.',
    it: 'Cetrioli croccanti di campo per HORECA e retail.',
    es: 'Pepinos crujientes de campo para HORECA y retail.',
  },
  'Dried shelled hazelnuts, export grade.': {
    ka: 'გაშრობილი გაცლილი თხილი, საექსპორტო კლასი.',
    ru: 'Сушёный очищенный фундук экспортного качества.',
    de: 'Getrocknete geschälte Haselnüsse, Exportqualität.',
    fr: 'Noisettes décortiquées séchées, qualité export.',
    it: 'Nocciole sgusciate essiccate, qualità export.',
    es: 'Avellanas sin cáscara secas, calidad exportación.',
  },
  'Air-dried walnuts, sorted for wholesale buyers.': {
    ka: 'ჰაერზე გამშრალი კაკალი, დახარისხებული საბითუმო მყიდველებისთვის.',
    ru: 'Воздушно-сушёный грецкий орех, отобранный для оптовиков.',
    de: 'Luftgetrocknete Walnüsse, sortiert für Großhändler.',
    fr: 'Noix séchées à l’air, triées pour les grossistes.',
    it: 'Noci essiccate all’aria, selezionate per grossisti.',
    es: 'Nueces secadas al aire, clasificadas para mayoristas.',
  },
  'Lightly roasted almond kernels for confectionery.': {
    ka: 'მსუბუკად შემწვარი ნუშის გული საკონდიტრო წარმოებისთვის.',
    ru: 'Слабо обжаренное миндальное ядро для кондитерского производства.',
    de: 'Leicht geröstete Mandelkerne für die Konditorei.',
    fr: 'Amandes légèrement torréfiées pour la confiserie.',
    it: 'Mandorle leggermente tostate per pasticceria.',
    es: 'Almendras ligeramente tostadas para confitería.',
  },
  'Amber-macerated Saperavi, bottled for export.': {
    ka: 'ქარვისფერად მაცერირებული საფერავი, დაბოთლილი ექსპორტისთვის.',
    ru: 'Саперави янтарной мацерации, разлито на экспорт.',
    de: 'Bernstein-mazerierter Saperavi, für den Export abgefüllt.',
    fr: 'Saperavi en macération ambrée, embouteillé pour l’export.',
    it: 'Saperavi a macerazione ambra, imbottigliato per l’export.',
    es: 'Saperavi de maceración ámbar, embotellado para exportación.',
  },
  'Crisp Rkatsiteli for restaurants and importers.': {
    ka: 'ხრაშუნა რქაწითელი რესტორნებისა და იმპორტიორებისთვის.',
    ru: 'Свежий Ркацители для ресторанов и импортёров.',
    de: 'Frischer Rkatsiteli für Restaurants und Importeure.',
    fr: 'Rkatsiteli frais pour restaurants et importateurs.',
    it: 'Rkatsiteli fresco per ristoranti e importatori.',
    es: 'Rkatsiteli fresco para restaurantes e importadores.',
  },
  'Fresh western Georgian white blend, screw-cap ready.': {
    ka: 'დასავლეთ საქართველოს ახალი თეთრი ნაზავი, screw-cap შეფუთვით.',
    ru: 'Свежий белый купаж Западной Грузии, готов к screw-cap.',
    de: 'Frischer westgeorgischer Weißwein-Cuvée, Schraubverschluss-fertig.',
    fr: 'Assemblage blanc frais d’ouest de la Géorgie, prêt pour capsule à vis.',
    it: 'Uvaggio bianco fresco dell’ovest georgiano, pronto per tappo a vite.',
    es: 'Coupage blanco fresco del oeste de Georgia, listo para tapón de rosca.',
  },
  'Pale dry rosé from estate Saperavi grapes.': {
    ka: 'ღია მშრალი როზე მამულის საფერავის ყურძნისგან.',
    ru: 'Светлое сухое розе из собственного винограда Саперави.',
    de: 'Helles trockenes Rosé aus eigenen Saperavi-Trauben.',
    fr: 'Rosé sec pâle issu de raisins Saperavi du domaine.',
    it: 'Rosato secco chiaro da uve Saperavi di proprietà.',
    es: 'Rosado seco pálido de uvas Saperavi de la finca.',
  },
  'Traditional salted guda cheese, vacuum packed.': {
    ka: 'ტრადიციული დამარილებული გუდის ყველი, ვაკუუმ შეფუთვაში.',
    ru: 'Традиционный солёный сыр гуда в вакуумной упаковке.',
    de: 'Traditioneller gesalzener Guda-Käse, vakuumverpackt.',
    fr: 'Fromage guda salé traditionnel, emballé sous vide.',
    it: 'Formaggio guda salato tradizionale, sottovuoto.',
    es: 'Queso guda salado tradicional, envasado al vacío.',
  },
  'Traditional cultured matsoni in retail jars.': {
    ka: 'ტრადიციული მაწონი საცალო ქილებში.',
    ru: 'Традиционный мацони в розничных банках.',
    de: 'Traditioneller Matsoni in Einzelhandelsgläsern.',
    fr: 'Matsoni traditionnel en pots retail.',
    it: 'Matsoni tradizionale in vasetti retail.',
    es: 'Matsoni tradicional en tarros para retail.',
  },
  'Daily fresh sulguni cheese, chilled logistics.': {
    ka: 'ყოველდღიური ახალი სულგუნი, გაგრილებული ლოგისტიკა.',
    ru: 'Ежедневно свежий сулугуни, охлаждаемая логистика.',
    de: 'Täglich frischer Sulguni, gekühlte Logistik.',
    fr: 'Sulguni frais du jour, logistique réfrigérée.',
    it: 'Sulguni fresco giornaliero, logistica refrigerata.',
    es: 'Sulguni fresco diario, logística refrigerada.',
  },
  'Raw multifloral honey from Racha pastures.': {
    ka: 'ნედლი მრავალყვავილოვანი თაფლი რაჭის საძოვრებიდან.',
    ru: 'Натуральный разнотравный мёд с пастбищ Рачи.',
    de: 'Roher Blütenhonig von den Weiden Rachas.',
    fr: 'Miel brut toutes fleurs des pâturages de Racha.',
    it: 'Miele crudo millefiori dai pascoli di Racha.',
    es: 'Miel cruda multifloral de los pastos de Racha.',
  },
  'Dark aromatic chestnut honey, glass jars.': {
    ka: 'მუქი არომატული წაბლის თაფლი, მინის ქილებში.',
    ru: 'Тёмный ароматный каштановый мёд в стеклянных банках.',
    de: 'Dunkler aromatischer Kastanienhonig in Gläsern.',
    fr: 'Miel de châtaignier sombre et aromatique, en pots en verre.',
    it: 'Miele di castagno scuro e aromatico in vasetti di vetro.',
    es: 'Miel de castaño oscura y aromática en tarros de vidrio.',
  },
  'Mild light acacia honey, filtered and bottled.': {
    ka: 'რბილი ღია აკაციის თაფლი, გაფილტრული და დაბოთლილი.',
    ru: 'Мягкий светлый акациевый мёд, фильтрованный и разлитый.',
    de: 'Milder heller Akazienhonig, gefiltert und abgefüllt.',
    fr: 'Miel d’acacia doux et clair, filtré et embouteillé.',
    it: 'Miele di acacia delicato e chiaro, filtrato e invasettato.',
    es: 'Miel de acacia suave y clara, filtrada y envasada.',
  },
  'Seasonal wildflower honey, creamed option available.': {
    ka: 'სეზონური ველური ყვავილების თაფლი, ხელმისაწვდომია კრემისებრი ვარიანტი.',
    ru: 'Сезонный разнотравный мёд, доступен кремовый вариант.',
    de: 'Saisonaler Blütenhonig, auch als cremige Variante.',
    fr: 'Miel de fleurs sauvages de saison, version crémeuse disponible.',
    it: 'Miele di fiori selvatici di stagione, disponibile anche cremoso.',
    es: 'Miel de flores silvestres de temporada; opción cremosa disponible.',
  },
  'Firm blueberries packed for fresh retail and freezing.': {
    ka: 'მკვრივი მოცვი შეფუთული ახალი რითეილისა და გაყინვისთვის.',
    ru: 'Плотная черника в упаковке для свежей розницы и заморозки.',
    de: 'Feste Heidelbeeren, verpackt für Frischhandel und Tiefkühlung.',
    fr: 'Myrtilles fermes emballées pour le frais et la congélation.',
    it: 'Mirtilli sodi confezionati per fresco e surgelazione.',
    es: 'Arándanos firmes envasados para fresco y congelación.',
  },
  'Same-day harvest raspberries in ventilated trays.': {
    ka: 'იმავე დღეს მოკრეფილი ჟოლო ვენტილირებად უჯრებში.',
    ru: 'Малина сбора того же дня в вентилируемых лотках.',
    de: 'Himbeeren vom Erntetag in belüfteten Schalen.',
    fr: 'Framboises récoltées le jour même en barquettes ventilées.',
    it: 'Lamponi raccolti lo stesso giorno in vassoi ventilati.',
    es: 'Frambuesas cosechadas el mismo día en bandejas ventiladas.',
  },
  'Sweet early strawberries for regional buyers.': {
    ka: 'ტკბილი ადრეული მარწყვი რეგიონული მყიდველებისთვის.',
    ru: 'Сладкая ранняя клубника для региональных покупателей.',
    de: 'Süße frühe Erdbeeren für regionale Käufer.',
    fr: 'Fraises précoces sucrées pour acheteurs régionaux.',
    it: 'Fragole precoci dolci per acquirenti regionali.',
    es: 'Fresas tempranas dulces para compradores regionales.',
  },
  'Naturally carbonated mineral water, 0.5–1.5 L bottles.': {
    ka: 'ბუნებრივად გაზიანი მინერალური წყალი, ბოთლები 0.5–1.5 ლ.',
    ru: 'Натурально газированная минеральная вода, бутылки 0,5–1,5 л.',
    de: 'Natürlich kohlensäurehaltiges Mineralwasser, 0,5–1,5-l-Flaschen.',
    fr: 'Eau minérale naturellement gazeuse, bouteilles 0,5–1,5 L.',
    it: 'Acqua minerale naturalmente frizzante, bottiglie da 0,5–1,5 L.',
    es: 'Agua mineral naturalmente carbonatada, botellas de 0,5–1,5 L.',
  },
  'Low-mineralization still water in PET and glass.': {
    ka: 'დაბალი მინერალიზაციის უგაზო წყალი PET-სა და მინაში.',
    ru: 'Негазированная вода низкой минерализации в ПЭТ и стекле.',
    de: 'Stilles Wasser mit geringer Mineralisierung in PET und Glas.',
    fr: 'Eau plate à faible minéralisation en PET et verre.',
    it: 'Acqua naturale a bassa mineralizzazione in PET e vetro.',
    es: 'Agua sin gas de baja mineralización en PET y vidrio.',
  },
  'Utskho suneli / blue fenugreek for spice blends.': {
    ka: 'უცხო სუნელი სანელებლების ნაზავებისთვის.',
    ru: 'Уцхо-сунели / голубой пажитник для пряных смесей.',
    de: 'Utskho-Suneli / blauer Bockshornklee für Gewürzmischungen.',
    fr: 'Utskho suneli / fenugrec bleu pour mélanges d’épices.',
    it: 'Utskho suneli / fieno greco blu per miscele di spezie.',
    es: 'Utskho suneli / alholva azul para mezclas de especias.',
  },
  'Mountain thyme and savory for spice importers.': {
    ka: 'მთის ურცი და ქონდარი სანელებლების იმპორტიორებისთვის.',
    ru: 'Горный тимьян и чабер для импортёров специй.',
    de: 'Bergthymian und Bohnenkraut für Gewürzimporteure.',
    fr: 'Thym et sarriette de montagne pour importateurs d’épices.',
    it: 'Timo e santoreggia di montagna per importatori di spezie.',
    es: 'Tomillo y ajedrea de montaña para importadores de especias.',
  },
  'Traditional adjika dry blend for food processors.': {
    ka: 'ტრადიციული აჯიკის მშრალი ნაზავი კვების გადამამუშავებლებისთვის.',
    ru: 'Традиционная сухая смесь аджики для пищевых производств.',
    de: 'Traditionelle trockene Adschika-Mischung für Lebensmittelhersteller.',
    fr: 'Mélange sec d’adjika traditionnel pour transformateurs alimentaires.',
    it: 'Miscela secca tradizionale di adjika per trasformatori alimentari.',
    es: 'Mezcla seca tradicional de adjika para procesadores de alimentos.',
  },
  'Orthodox leaf black tea, export-ready packing.': {
    ka: 'ორთოდოქსული ფოთლოვანი შავი ჩაი, საექსპორტო შეფუთვა.',
    ru: 'Чёрный листовой чай orthodox, упаковка готова к экспорту.',
    de: 'Orthodoxer Blatt-Schwarztee, exportfertige Verpackung.',
    fr: 'Thé noir feuille orthodox, emballage prêt à l’export.',
    it: 'Tè nero in foglia orthodox, confezione pronta per l’export.',
    es: 'Té negro en hoja orthodox, embalaje listo para exportación.',
  },
  'Light green tea with floral notes, bulk and retail packs.': {
    ka: 'ღია მწვანე ჩაი ყვავილოვანი ნოტებით, ნაყარი და საცალო შეფუთვა.',
    ru: 'Лёгкий зелёный чай с цветочными нотами, опт и розница.',
    de: 'Leichter Grüntee mit Blütennoten, Bulk- und Retail-Packungen.',
    fr: 'Thé vert léger aux notes florales, vrac et packs retail.',
    it: 'Tè verde leggero con note floreali, sfuso e confezioni retail.',
    es: 'Té verde ligero con notas florales, a granel y packs retail.',
  },
  'Whole dried bay leaves, sorted for food industry use.': {
    ka: 'მთლიანი გამშრალი დაფნის ფოთოლი, დახარისხებული კვების ინდუსტრიისთვის.',
    ru: 'Цельный сушёный лавровый лист, отобранный для пищевой промышленности.',
    de: 'Ganze getrocknete Lorbeerblätter, sortiert für die Lebensmittelindustrie.',
    fr: 'Feuilles de laurier séchées entières, triées pour l’industrie alimentaire.',
    it: 'Foglie di alloro essiccate intere, selezionate per l’industria alimentare.',
    es: 'Hojas de laurel secas enteras, clasificadas para la industria alimentaria.',
  },
  'Large whole leaves with strong aroma, bulk bags.': {
    ka: 'დიდი მთლიანი ფოთლები ძლიერი არომატით, ნაყარი ტომრები.',
    ru: 'Крупный цельный лист с сильным ароматом, мешки оптом.',
    de: 'Große ganze Blätter mit starkem Aroma, Bulk-Säcke.',
    fr: 'Grandes feuilles entières au fort arôme, sacs en vrac.',
    it: 'Foglie intere grandi dal forte aroma, sacchi sfusi.',
    es: 'Hojas enteras grandes de aroma intenso, sacos a granel.',
  },
  'Steam-distilled lavender oil for cosmetics and wellness.': {
    ka: 'ორთქლით გამოხდილი ლავანდის ზეთი კოსმეტიკისა და ველნესისთვის.',
    ru: 'Эфирное масло лаванды паровой дистилляции для косметики и wellness.',
    de: 'Wasserdampfdestilliertes Lavendelöl für Kosmetik und Wellness.',
    fr: 'Huile de lavande distillée à la vapeur pour cosmétique et bien-être.',
    it: 'Olio di lavanda distillato a vapore per cosmesi e wellness.',
    es: 'Aceite de lavanda destilado al vapor para cosmética y wellness.',
  },
  'Cold-pressed mandarin oil for fragrance and food use.': {
    ka: 'ცივად დაწურული მანდარინის ზეთი სურნელისა და საკვებისთვის.',
    ru: 'Холоднопрессованное масло мандарина для ароматов и пищевого применения.',
    de: 'Kaltgepresstes Mandarinenöl für Duft und Lebensmittel.',
    fr: 'Huile de mandarine pressée à froid pour parfum et usage alimentaire.',
    it: 'Olio di mandarino spremuto a freddo per fragranza e uso alimentare.',
    es: 'Aceite de mandarina prensado en frío para fragancia y uso alimentario.',
  },
  'Seasonal organic crate for retailers and restaurants.': {
    ka: 'სეზონური ორგანული ყუთი რითეილერებისა და რესტორნებისთვის.',
    ru: 'Сезонный органический ящик для ритейлеров и ресторанов.',
    de: 'Saisonale Bio-Kiste für Einzelhändler und Restaurants.',
    fr: 'Caisse bio de saison pour détaillants et restaurants.',
    it: 'Cassa biologica di stagione per rivenditori e ristoranti.',
    es: 'Caja ecológica de temporada para minoristas y restaurantes.',
  },
  'Certified organic apples, graded for fresh market.': {
    ka: 'სერტიფიცირებული ორგანული ვაშლი, დახარისხებული ახალი ბაზრისთვის.',
    ru: 'Сертифицированные органические яблоки, калиброванные для свежего рынка.',
    de: 'Zertifizierte Bio-Äpfel, sortiert für den Frischmarkt.',
    fr: 'Pommes bio certifiées, calibrées pour le marché du frais.',
    it: 'Mele biologiche certificate, calibrate per il mercato fresco.',
    es: 'Manzanas ecológicas certificadas, calibradas para mercado fresco.',
  },
  'Organic-certified wildflower honey in bulk jars.': {
    ka: 'ორგანულად სერტიფიცირებული ყვავილების თაფლი ნაყარ ქილებში.',
    ru: 'Органически сертифицированный разнотравный мёд в оптовых банках.',
    de: 'Bio-zertifizierter Blütenhonig in Großgebinden.',
    fr: 'Miel de fleurs sauvages certifié bio en pots vrac.',
    it: 'Miele di fiori selvatici certificato bio in barattoli sfusi.',
    es: 'Miel de flores silvestres con certificación ecológica en tarros a granel.',
  },
};

/** Resolve a product description for the active UI locale; falls back to the stored text. */
export function localizeProductDescription(
  description: string | null | undefined,
  locale: string | null | undefined,
): string {
  if (!description) return '';
  const resolved: Locale = locale && isLocale(locale) ? locale : DEFAULT_LOCALE;
  if (resolved === 'en') return description;
  return PRODUCT_DESCRIPTION_I18N[description]?.[resolved] ?? description;
}
