import { DEFAULT_LOCALE, isLocale, type Locale } from './locales';

/** Canonical English title → localized display titles (en omitted; falls back to key). */
export const PRODUCT_TITLE_I18N: Record<string, Partial<Record<Locale, string>>> = {
  'Fresh Kakheti peaches': {
    ka: 'კახეთის ახალი ატამი',
    ru: 'Свежие персики из Кахетии',
    de: 'Frische Kakheti-Pfirsiche',
    fr: 'Pêches fraîches de Kakheti',
    it: 'Pesche fresche di Kakheti',
    es: 'Melocotones frescos de Kakheti',
  },
  'Guria mandarins': {
    ka: 'გურიის მანდარინი',
    ru: 'Мандарины из Гурии',
    de: 'Guria-Mandarinen',
    fr: 'Mandarines de Guria',
    it: 'Mandarini di Guria',
    es: 'Mandarinas de Guria',
  },
  'Kartli dessert apples': {
    ka: 'ქართლის დესერტული ვაშლი',
    ru: 'Десертные яблоки из Картли',
    de: 'Kartli-Dessertäpfel',
    fr: 'Pommes dessert de Kartli',
    it: 'Mele dessert di Kartli',
    es: 'Manzanas de postre de Kartli',
  },
  'Kakheti persimmons': {
    ka: 'კახეთის ხურმა',
    ru: 'Хурма из Кахетии',
    de: 'Kakheti-Kakis',
    fr: 'Kakis de Kakheti',
    it: 'Cachi di Kakheti',
    es: 'Caquis de Kakheti',
  },
  'Greenhouse tomatoes': {
    ka: 'სათბურის პომიდორი',
    ru: 'Тепличные томаты',
    de: 'Gewächshaustomaten',
    fr: 'Tomates de serre',
    it: 'Pomodori da serra',
    es: 'Tomates de invernadero',
  },
  'Imereti potatoes': {
    ka: 'იმერეთის კარტოფილი',
    ru: 'Картофель из Имерети',
    de: 'Imereti-Kartoffeln',
    fr: 'Pommes de terre d’Iméréti',
    it: 'Patate di Imereti',
    es: 'Patatas de Imereti',
  },
  'Sweet peppers mix': {
    ka: 'ტკბილი წიწაკის ნაზავი',
    ru: 'Смесь сладкого перца',
    de: 'Süßpaprika-Mix',
    fr: 'Mélange de poivrons doux',
    it: 'Mix di peperoni dolci',
    es: 'Mezcla de pimientos dulces',
  },
  'Fresh cucumbers': {
    ka: 'ახალი კიტრი',
    ru: 'Свежие огурцы',
    de: 'Frische Gurken',
    fr: 'Concombres frais',
    it: 'Cetrioli freschi',
    es: 'Pepinos frescos',
  },
  'Georgian hazelnuts (shelled)': {
    ka: 'ქართული თხილი (გაცლილი)',
    ru: 'Грузинский фундук (очищенный)',
    de: 'Georgische Haselnüsse (geschält)',
    fr: 'Noisettes géorgiennes (décortiquées)',
    it: 'Nocciole georgiane (sgusciate)',
    es: 'Avellanas georgianas (sin cáscara)',
  },
  'In-shell walnuts': {
    ka: 'ნაჭუჭიანი კაკალი',
    ru: 'Грецкий орех в скорлупе',
    de: 'Walnüsse in der Schale',
    fr: 'Noix en coque',
    it: 'Noci in guscio',
    es: 'Nueces con cáscara',
  },
  'Roasted almond kernels': {
    ka: 'შემწვარი ნუშის გული',
    ru: 'Жареное миндальное ядро',
    de: 'Geröstete Mandelkerne',
    fr: 'Amandes grillées',
    it: 'Mandorle tostate',
    es: 'Almendras tostadas',
  },
  'Saperavi qvevri 2024': {
    ka: 'საფერავი ქვევრი 2024',
    ru: 'Саперави квеври 2024',
    de: 'Saperavi Qvevri 2024',
    fr: 'Saperavi qvevri 2024',
    it: 'Saperavi qvevri 2024',
    es: 'Saperavi qvevri 2024',
  },
  'Rkatsiteli white wine': {
    ka: 'რქაწითელი თეთრი ღვინო',
    ru: 'Белое вино Ркацители',
    de: 'Rkatsiteli-Weißwein',
    fr: 'Vin blanc Rkatsiteli',
    it: 'Vino bianco Rkatsiteli',
    es: 'Vino blanco Rkatsiteli',
  },
  'Tsitska-Tsolikouri blend': {
    ka: 'ციცქა-ცოლიკოურის ნაზავი',
    ru: 'Купаж Цицка–Цоликоури',
    de: 'Tsitska-Tsolikouri-Cuvée',
    fr: 'Assemblage Tsitska-Tsolikouri',
    it: 'Uvaggio Tsitska-Tsolikouri',
    es: 'Coupage Tsitska-Tsolikouri',
  },
  'Dry Saperavi rosé': {
    ka: 'მშრალი საფერავის როზე',
    ru: 'Сухое розе Саперави',
    de: 'Trockener Saperavi-Rosé',
    fr: 'Rosé sec Saperavi',
    it: 'Rosato secco Saperavi',
    es: 'Rosado seco Saperavi',
  },
  'Guda sheep cheese': {
    ka: 'გუდის ცხვრის ყველი',
    ru: 'Овечий сыр гуда',
    de: 'Guda-Schafskäse',
    fr: 'Fromage de brebis guda',
    it: 'Formaggio di pecora guda',
    es: 'Queso de oveja guda',
  },
  'Farm matsoni': {
    ka: 'ფერმერული მაწონი',
    ru: 'Фермерский мацони',
    de: 'Bauernhof-Matsoni',
    fr: 'Matsoni fermier',
    it: 'Matsoni di fattoria',
    es: 'Matsoni de granja',
  },
  'Fresh sulguni': {
    ka: 'ახალი სულგუნი',
    ru: 'Свежий сулугуни',
    de: 'Frischer Sulguni',
    fr: 'Sulguni frais',
    it: 'Sulguni fresco',
    es: 'Sulguni fresco',
  },
  'Racha mountain honey': {
    ka: 'რაჭის მთის თაფლი',
    ru: 'Горный мёд из Рачи',
    de: 'Racha-Berghonig',
    fr: 'Miel de montagne de Racha',
    it: 'Miele di montagna di Racha',
    es: 'Miel de montaña de Racha',
  },
  'Chestnut blossom honey': {
    ka: 'წაბლის ყვავილის თაფლი',
    ru: 'Мёд с цветков каштана',
    de: 'Kastanienblütenhonig',
    fr: 'Miel de fleurs de châtaignier',
    it: 'Miele di fiori di castagno',
    es: 'Miel de flor de castaño',
  },
  'Acacia honey': {
    ka: 'აკაციის თაფლი',
    ru: 'Акациевый мёд',
    de: 'Akazienhonig',
    fr: 'Miel d’acacia',
    it: 'Miele di acacia',
    es: 'Miel de acacia',
  },
  'Highland wildflower honey': {
    ka: 'მაღალმთის ყვავილების თაფლი',
    ru: 'Горный разнотравный мёд',
    de: 'Hochland-Blütenhonig',
    fr: 'Miel de fleurs des hauts plateaux',
    it: 'Miele di fiori di alta montagna',
    es: 'Miel de flores de alta montaña',
  },
  'Adjara blueberries': {
    ka: 'აჭარის მოცვი',
    ru: 'Черника из Аджарии',
    de: 'Adscharien-Heidelbeeren',
    fr: 'Myrtilles d’Adjarie',
    it: 'Mirtilli di Adjara',
    es: 'Arándanos de Adjara',
  },
  'Fresh raspberries': {
    ka: 'ახალი ჟოლო',
    ru: 'Свежая малина',
    de: 'Frische Himbeeren',
    fr: 'Framboises fraîches',
    it: 'Lamponi freschi',
    es: 'Frambuesas frescas',
  },
  'Guria strawberries': {
    ka: 'გურიის მარწყვი',
    ru: 'Клубника из Гурии',
    de: 'Guria-Erdbeeren',
    fr: 'Fraises de Guria',
    it: 'Fragole di Guria',
    es: 'Fresas de Guria',
  },
  'Natural sparkling mineral water': {
    ka: 'ნატურალური გაზიანი მინერალური წყალი',
    ru: 'Натуральная газированная минеральная вода',
    de: 'Natürliches Sprudel-Mineralwasser',
    fr: 'Eau minérale naturelle gazeuse',
    it: 'Acqua minerale naturale frizzante',
    es: 'Agua mineral natural con gas',
  },
  'Still mineral water': {
    ka: 'უგაზო მინერალური წყალი',
    ru: 'Негазированная минеральная вода',
    de: 'Stilles Mineralwasser',
    fr: 'Eau minérale plate',
    it: 'Acqua minerale naturale',
    es: 'Agua mineral sin gas',
  },
  'Dried Georgian blue fenugreek': {
    ka: 'გამშრალი ქართული უცხო სუნელი',
    ru: 'Сушёный грузинский уцхо-сунели',
    de: 'Getrockneter georgischer Blauer Bockshornklee',
    fr: 'Fenugrec bleu géorgien séché',
    it: 'Fieno greco blu georgiano essiccato',
    es: 'Alholva azul georgiana seca',
  },
  'Dried thyme and savory mix': {
    ka: 'გამშრალი ურცისა და ქონდარის ნაზავი',
    ru: 'Смесь сушёного тимьяна и чабера',
    de: 'Getrockneter Thymian-Bohnenkraut-Mix',
    fr: 'Mélange de thym et sarriette séchés',
    it: 'Mix di timo e santoreggia essiccati',
    es: 'Mezcla de tomillo y ajedrea secos',
  },
  'Dried adjika spice blend': {
    ka: 'გამშრალი აჯიკის სანელებლის ნაზავი',
    ru: 'Сушёная смесь специй аджика',
    de: 'Getrocknete Adschika-Gewürzmischung',
    fr: 'Mélange d’épices adjika séché',
    it: 'Miscela di spezie adjika essiccata',
    es: 'Mezcla de especias adjika seca',
  },
  'Guria black tea': {
    ka: 'გურიის შავი ჩაი',
    ru: 'Чёрный чай из Гурии',
    de: 'Guria-Schwarztee',
    fr: 'Thé noir de Guria',
    it: 'Tè nero di Guria',
    es: 'Té negro de Guria',
  },
  'Georgian green tea': {
    ka: 'ქართული მწვანე ჩაი',
    ru: 'Грузинский зелёный чай',
    de: 'Georgischer Grüntee',
    fr: 'Thé vert géorgien',
    it: 'Tè verde georgiano',
    es: 'Té verde georgiano',
  },
  'Dried bay leaves': {
    ka: 'გამშრალი დაფნის ფოთოლი',
    ru: 'Сушёный лавровый лист',
    de: 'Getrocknete Lorbeerblätter',
    fr: 'Feuilles de laurier séchées',
    it: 'Foglie di alloro essiccate',
    es: 'Hojas de laurel secas',
  },
  'Premium bay leaf grade A': {
    ka: 'პრემიუმ დაფნის ფოთოლი, კლასი A',
    ru: 'Премиальный лавровый лист, класс A',
    de: 'Premium-Lorbeerblatt Klasse A',
    fr: 'Feuille de laurier premium grade A',
    it: 'Alloro premium grado A',
    es: 'Hoja de laurel premium grado A',
  },
  'Lavender essential oil': {
    ka: 'ლავანდის ეთერზეთი',
    ru: 'Эфирное масло лаванды',
    de: 'Ätherisches Lavendelöl',
    fr: 'Huile essentielle de lavande',
    it: 'Olio essenziale di lavanda',
    es: 'Aceite esencial de lavanda',
  },
  'Mandarin peel essential oil': {
    ka: 'მანდარინის ქერქის ეთერზეთი',
    ru: 'Эфирное масло кожуры мандарина',
    de: 'Ätherisches Öl aus Mandarinenschalen',
    fr: 'Huile essentielle de zeste de mandarine',
    it: 'Olio essenziale di scorza di mandarino',
    es: 'Aceite esencial de cáscara de mandarina',
  },
  'Organic mixed vegetables': {
    ka: 'ორგანული ბოსტნეულის ნაზავი',
    ru: 'Органический овощной микс',
    de: 'Bio-Gemüsemischung',
    fr: 'Légumes bio mélangés',
    it: 'Verdure miste biologiche',
    es: 'Verduras mixtas ecológicas',
  },
  'Organic dessert apples': {
    ka: 'ორგანული დესერტული ვაშლი',
    ru: 'Органические десертные яблоки',
    de: 'Bio-Dessertäpfel',
    fr: 'Pommes dessert bio',
    it: 'Mele dessert biologiche',
    es: 'Manzanas de postre ecológicas',
  },
  'Organic wildflower honey': {
    ka: 'ორგანული ყვავილების თაფლი',
    ru: 'Органический разнотравный мёд',
    de: 'Bio-Blütenhonig',
    fr: 'Miel de fleurs sauvages bio',
    it: 'Miele di fiori selvatici biologico',
    es: 'Miel de flores silvestres ecológica',
  },
  'Export-grade blueberries': {
    ka: 'საექსპორტო მოცვი',
    ru: 'Черника экспортного качества',
    de: 'Export-Heidelbeeren',
    fr: 'Myrtilles qualité export',
    it: 'Mirtilli qualità export',
    es: 'Arándanos de calidad exportación',
  },
  'Saperavi wine for retail': {
    ka: 'საფერავის ღვინო რითეილისთვის',
    ru: 'Вино Саперави для ритейла',
    de: 'Saperavi-Wein für den Einzelhandel',
    fr: 'Vin Saperavi pour la vente au détail',
    it: 'Vino Saperavi per il retail',
    es: 'Vino Saperavi para retail',
  },
  'Mountain flower honey': {
    ka: 'მთის ყვავილების თაფლი',
    ru: 'Горный цветочный мёд',
    de: 'Bergblütenhonig',
    fr: 'Miel de fleurs de montagne',
    it: 'Miele di fiori di montagna',
    es: 'Miel de flores de montaña',
  },
  'Natural mineral water': {
    ka: 'ნატურალური მინერალური წყალი',
    ru: 'Натуральная минеральная вода',
    de: 'Natürliches Mineralwasser',
    fr: 'Eau minérale naturelle',
    it: 'Acqua minerale naturale',
    es: 'Agua mineral natural',
  },
};

/** Resolve a product title for the active UI locale; falls back to the stored title. */
export function localizeProductTitle(
  title: string | null | undefined,
  locale: string | null | undefined,
): string {
  if (!title) return '';
  const resolved: Locale = locale && isLocale(locale) ? locale : DEFAULT_LOCALE;
  if (resolved === 'en') return title;
  return PRODUCT_TITLE_I18N[title]?.[resolved] ?? title;
}
